package com.example.satadelivery.models.branch_orders

data class Restaurant(
    var account_manager_id: Int,
    var archived: Int,
    var category_id: Int,
    var comment: String,
    var content_id: Int,
    var cover: String,
    var created: String,
    var delivery_time: Int,
    var departments_id: Int,
    var discount_from: String,
    var discount_percentage: Int,
    var discount_to: String,
    var email: String,
    var expr_liences: String,
    var expr_taxescarr: String,
    var id: Int,
    var license_number: String,
    var logo: String,
    var minimum: Int,
    var modified: String,
    var name: String,
    var name_en: String,
    var position: Int,
    var refuse_approve_reasons_id: Int,
    var restaurant_general_status_id: Int,
    var restaurants_status_id: Int,
    var restaurants_types_id: Int,
    var sales_id: Int,
    var taxes: Int,
    var taxes_number: String,
    var user_id: Int
)